version: '3.4'

services:
  trace.tests:
    image: ${DOCKER_REGISTRY-}trace
    build:
      context: .
      dockerfile: Trace.Tests/Dockerfile
    environment:
      JAEGER_SERVICE_NAME: trace.tests
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: const
      JAEGER_PROPAGATION: b3

  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  grafana:
    image: grafana/grafana:7.0.0
    depends_on:
      - jaeger
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana

  trace.api.tests:
    image: ${DOCKER_REGISTRY-}traceapi
    build:
      context: .
      dockerfile: Trace.Api.Tests/Dockerfile
    environment:
      JAEGER_SERVICE_NAME: trace.api.tests
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: const
      JAEGER_PROPAGATION: b3

